version: '3.9'
services:
  app:
    build:
      context: .
    env_file:
        - .env
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: on-failure
    command: >
      sh -c "npm run start"
    depends_on:
      - db

  db:
    image: mongo
    restart: on-failure
    ports:
      - '27018:27017'
    env_file:
      - .env
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_db:/data/db
